// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxi8i3jxdUMCLDrNBsYe4g2YcqRFeQHpo',
    appId: '1:936460764842:web:1bce6c2a09ca57cdeeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    authDomain: 'delivery-sopetran.firebaseapp.com',
    storageBucket: 'delivery-sopetran.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCle6Q0II3LrcxWzJAxKFKte53MpZdW_q8',
    appId: '1:936460764842:android:8cf8e95d1e8d4f7ceeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    storageBucket: 'delivery-sopetran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTqH2Dqq4rc-kFeX3J4C4e2YmorQjfAg',
    appId: '1:936460764842:ios:8dfd8f9a4921aa38eeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    storageBucket: 'delivery-sopetran.appspot.com',
    iosBundleId: 'com.example.vendors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTqH2Dqq4rc-kFeX3J4C4e2YmorQjfAg',
    appId: '1:936460764842:ios:b59371062815018ceeb2d3',
    messagingSenderId: '936460764842',
    projectId: 'delivery-sopetran',
    storageBucket: 'delivery-sopetran.appspot.com',
    iosBundleId: 'com.example.vendors.RunnerTests',
  );
}
